authapp/urls.py
from django.urls import path
from . import views

app_name = 'authapp'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout')
]

django_coding_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('auth/', include('authapp.urls'))
]

tasks/urls.py
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.home, name='home')
]

authapp/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=False, null=False)
    due_date = models.DateTimeField()
    create_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user')
    priority = models.CharField(max_length=10, choices=(
        ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')))
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Image(models.Model):
    image = models.ImageField(upload_to='uploads/tasks')
    task = models.ForeignKey(Task, on_delete=models.CASCADE)

    def __str__(self):
        return f"This image belongs to {self.task.title}"

authapp/forms.py
from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "username", "password")

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Enter Password'}))
    confirm_password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Repeat Password'}))

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs = {'placeholder': 'First Name'}
        self.fields['last_name'].widget.attrs = {'placeholder': 'Last Name'}
        self.fields['username'].widget.attrs = {'placeholder': 'Username'}
        self.fields['email'].widget.attrs = {'placeholder': 'Email'}

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields[field].widget.attrs['required'] = True

    def clean(self):
        password = self.cleaned_data["password"]
        confirm_password = self.cleaned_data["confirm_password"]

        if len(password) < 6:
            self.errors['password'] = 'Password should be at least 6 characters'
            raise forms.ValidationError(
                'Password should be at least 6 characters')

        if password != confirm_password:
            self.errors['password'] = 'Passwords did not match'
            raise forms.ValidationError('Passwords did not match')


class LoginForm(forms.Form):
    username_or_email = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Enter Username or Email', 'id': 'usernameOrEmail', 'class': 'form-control', 'required': True}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Enter Password', 'id': 'password', 'class': 'form-control', 'required': True}))

authapp/views.py
from django.shortcuts import redirect, render
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import LoginForm, RegisterForm


def login(request):
    if request.user.is_authenticated:
        return redirect('tasks:home')

    context = dict()
    form = LoginForm()
    context['form'] = form

    if request.method == 'POST':
        form = LoginForm(request.POST)
        context['form'] = form

        if form.is_valid():
            username_or_email = form.cleaned_data['username_or_email']
            password = form.cleaned_data['password']

            user = auth.authenticate(
                request, username=username_or_email, password=password)

            if user is not None:
                auth.login(request, user)

                messages.success(request, 'Successfully Logged In!')
                return redirect('tasks:home')

            else:
                messages.error(request, 'Invalid credentials!')
                return render(request, 'authapp/login.html', context)

        else:
            messages.error(request, 'Invalid credentials!')
            return render(request, 'authapp/login.html', context)

    else:
        form = LoginForm()
        context['form'] = form

    return render(request, 'authapp/login.html', context)


def register(request):
    context = dict()
    form = RegisterForm()
    context['form'] = form

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        context['form'] = form

        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            try:
                user = User.objects.get(username=username)
                if user is not None:
                    form.errors['username'] = f'A user with user "{
                        username}" already exists.'
                    return render(request, 'authapp/register.html', context)
            except:
                pass

            try:
                user = User.objects.get(email=email)
                if user is not None:
                    form.errors['email'] = f'A user with email "{
                        email}" already exists.'
                    return render(request, 'authapp/register.html', context)
            except:
                pass

        else:
            messages.error(request, 'Something went wrong!')
            return render(request, 'authapp/register.html', context)

        user = User.objects.create_user(
            username=username, email=email, password=password)
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        messages.success(request, 'User Created Successfully!')

        return redirect('authapp:login')

    else:
        form = RegisterForm()
        context['form'] = form

    return render(request, 'authapp/register.html', context)


@login_required(login_url='authapp:login')
def logout(request):
    auth.logout(request)
    return redirect('authapp:login')

tasks/views.py
from django.shortcuts import render


def home(request):
    context = {}
    return render(request, 'home.html', context)

authapp/templates/authapp/login.html
{% extends "base.html" %}
{% block content %}
  <div class="max-w-xl w-full mx-auto p-4">
    <h1 class="text-center mb-5 text-4xl font-bold tracking-wide">Login to Create Task</h1>
    <form action="{% url "authapp:login" %}" method="post">
      {% csrf_token %}
      <div class="flex flex-col gap-5">
        <div class="flex flex-col gap-2">
          <label for="usernameOrEmail" class="form-label">{{ form.username_or_email.label }}</label>
          {{ form.username_or_email }}
        </div>
        <div class="flex flex-col gap-2">
          <label for="password" class="form-label">{{ form.password.label }}</label>
          {{ form.password }}
        </div>
        <button type="submit"
                class="text-white bg-black duration-200 transition-all ease-in-out rounded-md hover:opacity-80 py-2 uppercase px-10">
          Login
        </button>
      </form>
      <div class="flex gap-2 my-2">
        <p>Don't have any account?</p>
        <a href="{% url 'authapp:register' %}"
           class="text-blue-600 hover:underline">Register</a>
      </div>
    </div>
  </div>
{% endblock content %}

authapp/templates/authapp/register.html
{% extends "base.html" %}
{% block content %}
  <div class="max-w-xl w-full mx-auto p-4">
    <h1 class="text-center mb-5 text-4xl font-bold tracking-wide">Create Account</h1>
    <form method="post">
      {% csrf_token %}
      <div class="flex flex-col gap-5">
        {% for field in form %}
          <div class="flex flex-col gap-2">
            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
            {{ field }}
            {% if field.errors %}<small class="text-red-950">{{ field.errors|escape }}</small>{% endif %}
          </div>
        {% endfor %}
        <button type="submit"
                class="text-white bg-black duration-200 transition-all ease-in-out rounded-md hover:opacity-80 py-2 uppercase px-10">
          Register
        </button>
      </form>
      <div class="flex gap-2 my-2">
        <p>Already have an account?</p>
        <a href="{% url 'authapp:login' %}"
           class="text-blue-600 hover:underline">Login</a>
      </div>
    </div>
  </div>
{% endblock content %}

tasks/templates/home.html
{% extends "base.html" %}
{% block content %}
    <h1>Home Page</h1>
{% endblock content %}

tasks/templates/partials/form.html
<form>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email"
           class="form-control"
           id="exampleInputEmail1"
           aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Codemy Ecommerce</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static "assets/favicon.ico" %}" />
    <!-- Bootstrap icons-->
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static "css/output.css" %}" rel="stylesheet" />
  </head>
  <body>
    <!-- Navigation-->
    {% include "./partials/_navbar.html" %}
    <!-- Tailwindcss Toast Messages -->
    <section class="absolute top-2 right-5 shadow-sm">
      {% include "./partials/_messages.html" %}
    </section>
    <!-- Section-->
    <main class="py-5">
      {% block content %}
      {% endblock content %}
    </main>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p>
      </div>
    </footer>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
  </body>
</html>

templates/partials/_messages.html
{% if messages %}
  {% for message in messages %}
    {% if message.tags == 'success' %}
      <div id="toast-success"
           class="flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800"
           role="alert">
        <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-green-500 bg-green-100 rounded-lg dark:bg-green-800 dark:text-green-200">
          <svg class="w-5 h-5"
               aria-hidden="true"
               xmlns="http://www.w3.org/2000/svg"
               fill="currentColor"
               viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z" />
          </svg>
          <span class="sr-only">Check icon</span>
        </div>
        <div class="ms-3 text-sm font-normal">{{ message }}</div>
        <button type="button"
                class="ms-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700"
                data-dismiss-target="#toast-success"
                aria-label="Close">
          <span class="sr-only">Close</span>
          <svg class="w-3 h-3"
               aria-hidden="true"
               xmlns="http://www.w3.org/2000/svg"
               fill="none"
               viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
          </svg>
        </button>
      </div>
    {% endif %}
    {% if message.tags == 'error' %}
      <div id="toast-danger"
           class="flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800"
           role="alert">
        <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-red-500 bg-red-100 rounded-lg dark:bg-red-800 dark:text-red-200">
          <svg class="w-5 h-5"
               aria-hidden="true"
               xmlns="http://www.w3.org/2000/svg"
               fill="currentColor"
               viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 11.793a1 1 0 1 1-1.414 1.414L10 11.414l-2.293 2.293a1 1 0 0 1-1.414-1.414L8.586 10 6.293 7.707a1 1 0 0 1 1.414-1.414L10 8.586l2.293-2.293a1 1 0 0 1 1.414 1.414L11.414 10l2.293 2.293Z" />
          </svg>
          <span class="sr-only">Error icon</span>
        </div>
        <div class="ms-3 text-sm font-normal">{{ message }}</div>
        <button type="button"
                class="ms-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700"
                data-dismiss-target="#toast-danger"
                aria-label="Close">
          <span class="sr-only">Close</span>
          <svg class="w-3 h-3"
               aria-hidden="true"
               xmlns="http://www.w3.org/2000/svg"
               fill="none"
               viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
          </svg>
        </button>
      </div>
    {% endif %}
    {% if message.tags == 'warning' %}
      <div id="toast-warning"
           class="flex items-center w-full max-w-xs p-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800"
           role="alert">
        <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-orange-500 bg-orange-100 rounded-lg dark:bg-orange-700 dark:text-orange-200">
          <svg class="w-5 h-5"
               aria-hidden="true"
               xmlns="http://www.w3.org/2000/svg"
               fill="currentColor"
               viewBox="0 0 20 20">
            <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM10 15a1 1 0 1 1 0-2 1 1 0 0 1 0 2Zm1-4a1 1 0 0 1-2 0V6a1 1 0 0 1 2 0v5Z" />
          </svg>
          <span class="sr-only">Warning icon</span>
        </div>
        <div class="ms-3 text-sm font-normal">{{ message }}</div>
        <button type="button"
                class="ms-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700"
                data-dismiss-target="#toast-warning"
                aria-label="Close">
          <span class="sr-only">Close</span>
          <svg class="w-3 h-3"
               aria-hidden="true"
               xmlns="http://www.w3.org/2000/svg"
               fill="none"
               viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
          </svg>
        </button>
      </div>
    {% endif %}
  {% endfor %}
{% endif %}

templates/partials/_navbar.html
<nav class="flex items-center justify-between py-5 px-10 border-b-2 shadow-md">
  <div class="max-w-5xl w-full flex items-center justify-between gap-4">
    <a class="font-bold text-4xl tracking-wide"
       href="{% url "tasks:home" %}">Task Manager</a>
    <div class="flex items-center gap-2">
      <ul class="flex items-center gap-2">
        <li class="px-4">
          <a class="hover:text-slate-700 {% if request.path == '/' %}text-red-700{% endif %} "
             href="{% url "tasks:home" %}">Home</a>
        </li>
        <li class="px-4">
          <a class="hover:text-slate-700" href="#!">About</a>
        </li>
        <div class="flex items-center gap-2">
          {% if request.user.is_authenticated %}
            <a class="auth-btn text-white bg-black"
               href="{% url "authapp:logout" %}">Logout</a>
          {% else %}
            <a class="auth-btn {% if request.path == '/auth/login/' %}text-white bg-black {% else %} text-black bg-white{% endif %}"
               href="{% url "authapp:login" %}">Login</a>
            <a class="auth-btn {% if request.path == '/auth/register/' %}text-white bg-black {% else %} text-black bg-white{% endif %}"
               href="{% url "authapp:register" %}">Register</a>
          {% endif %}
        </div>
      </ul>
    </div>
  </div>
</nav>